### ISSUE TITLE
Can't create Item

### ISSUE THREAD

**Issue by mittus** [bigin/ItemManager_2.0#6] opened 2017-08-31 09:41 UTC
Hello!

I can't use construction:
$item = new Item(1);
$item->name = 'My item name';
$item->save();

In ItemManager nothing appears :(

List my all plugins: http://prntscr.com/gfb2cc
Category: http://prntscr.com/gfb2sy

**Comment by bigin** [comment] 2017-08-31 10:00
Everything works as usual here, do you get an error message?
Did you know that the "new Item(ID)" should contain an ID of an existing category?

**Comment by mittus** [comment] 2017-08-31 10:06
No, I haven't message, when I use this construction, nothing happens. I use id my category (1).

**Comment by bigin** [comment] 2017-08-31 10:11
I can't reproduce it, sorry. But ItemManager uses the same API function call to creating its items in admin area.

**Comment by mittus** [comment] 2017-08-31 10:15
Than'k you. I will search this problem and write here about this.

**Comment by bigin** [comment] 2017-08-31 10:18
Ok,
you can check whether your item object created before you save:

```
$item = new Item(your_cat_id);
$item->name = 'My item name';
Util::preformat($item);
```

**Comment by bigin** [comment] 2017-09-02 07:26
I will close this issue for now until I can reproduce this error again.

**Comment by mittus** [comment] 2017-09-02 08:17
Hello!

I can use this construction only with $imanager = new IManager(); 

It's work for me:
function test() {
	$imanager = new IManager();
	$item = new Item(1);
	$item->name = 'New Item';
	$item->save();
}

**Comment by bigin** [comment] 2017-09-02 08:24
Hmm, I thought you had already done that. Of course, you need to create an ItemManager instance first ;-)
Do this:
```
imanager();
$item = new Item(1);
$item->name = 'New Item';
$item->save();
```

`new IManager()` is deprecated

**Comment by mittus** [comment] 2017-09-02 08:27
Thank you very much, it's work!!

**Comment by bigin** [comment] 2017-09-02 08:28
You are welcome!

**Closed by bigin** 2017-09-02 08:28 UTC
